# Generated by Django 4.0 on 2022-05-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_linkedaccounts_last_history_id'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='linked_account',
            field=models.ForeignKey(
                default=14, on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedaccounts'),
            preserve_default=False,
        ),
    ]
