# Generated by Django 5.1.3 on 2025-01-18 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_linkedaccounts_use_contact_labels'),
        ('contacts', '0002_contact_linked_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_label_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_labels', to='accounts.linkedaccounts')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.label'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['linked_account', 'hashed_email'], name='contacts_co_linked__4aa2a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('gmail_label_id', 'linked_account')},
        ),
    ]
