# Generated by Django 5.1.3 on 2025-01-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_linkedaccounts_use_contact_labels'),
        ('contacts', '0003_label_contact_label_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('hashed_email', 'linked_account')},
        ),
        migrations.AddField(
            model_name='contact',
            name='labels',
            field=models.ManyToManyField(blank=True, to='contacts.label'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='label',
        ),
    ]
