# Generated by Django 4.1.1 on 2023-04-19 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0002_remove_referral_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='inviter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('inviter', 'referred_user')},
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_users',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='user',
        ),
    ]
