# Generated by Django 4.0 on 2022-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredemails',
            name='count_emails',
            field=models.IntegerField(default=1),
        ),
    ]
