# Generated by Django 4.0 on 2022-04-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_filteredemails_count_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filteredemails',
            old_name='date',
            new_name='date_filtered',
        ),
    ]
