# Generated by Django 4.0 on 2022-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_filteredemails_process_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filteredemails',
            old_name='linkedAccount',
            new_name='linked_account',
        ),
    ]
