# Generated by Django 4.0 on 2022-06-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_linkedaccounts_last_history_id'),
        ('dashboard', '0005_rename_linkedaccount_filteredemails_linked_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('watcher', 'WATCHER'), ('contact', 'CONTACT')], max_length=20)),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedaccounts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
