# Generated by Django 4.1.1 on 2023-10-06 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_linkedaccounts_whitelist_on_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDebugInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateField(auto_now_add=True)),
                ('process_status', models.CharField(choices=[('filtered', 'FILTERED'), ('passed', 'PASSED')], max_length=20)),
                ('debug_info', models.TextField()),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.linkedaccounts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
