# Generated by Django 4.1.1 on 2023-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_emaildebuginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildebuginfo',
            name='from_email_hashed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
