# Generated by Django 4.0 on 2022-05-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
