# Generated by Django 4.0 on 2022-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_linkedaccounts_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='archive_emails',
            field=models.BooleanField(default=True),
        ),
    ]
