# Generated by Django 4.0 on 2022-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_linkedaccounts_archive_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='last_history_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
