# Generated by Django 4.0 on 2022-07-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_deletedaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
