# Generated by Django 4.0 on 2022-07-31 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_linkedaccounts_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='whitelist_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
