# Generated by Django 4.0 on 2022-08-06 13:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_linkedaccounts_whitelist_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedaccounts',
            name='whitelist_domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
