# Generated by Django 4.1.1 on 2022-12-24 10:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_linkedaccounts_trash_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=accounts.models.generate_referral_code, max_length=50),
        ),
    ]
