# Generated by Django 4.1.1 on 2023-08-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='check_spam',
            field=models.BooleanField(default=False),
        ),
    ]
