# Generated by Django 4.1.1 on 2023-08-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_linkedaccounts_check_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paypal_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Paypal email address'),
        ),
    ]
