# Generated by Django 4.1.1 on 2023-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_paypal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='whitelist_on_label',
            field=models.BooleanField(default=False),
        ),
    ]
