# Generated by Django 4.1.1 on 2023-10-18 15:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='invites_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=accounts.models.generate_referral_code, max_length=50, unique=True),
        ),
    ]
