# Generated by Django 5.1.3 on 2025-01-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_linkedaccounts_invites_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccounts',
            name='use_contact_labels',
            field=models.BooleanField(default=False),
        ),
    ]
